# Generated by Django 2.2.3 on 2020-06-27 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type_of',
            field=models.CharField(choices=[('podcast', 'podcast'), ('article', 'article')], max_length=20),
        ),
    ]
