# Generated by Django 3.0.7 on 2020-10-28 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('type_of', models.CharField(choices=[('USER_FOLLOWED', 'USER_FOLLOWED'), ('SNIPPET_CREATED', 'SNIPPET_CREATED'), ('PERMISSION_GRANTED', 'PERMISSION_GRANTED'), ('PERMISSION_REVOKED', 'PERMISSION_REVOKED'), ('COMMENT_CREATED', 'COMMENT_CREATED'), ('NEW_FOLLOWER', 'NEW_FOLLOWER'), ('FOLLOWER_INTERACT', 'FOLLOWER_INTERACT')], max_length=20)),
                ('title', models.CharField(max_length=128)),
                ('identifier', models.BigIntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(default='', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
