# Generated by Django 2.2.3 on 2020-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='identifier',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of',
            field=models.CharField(choices=[('USER_FOLLOWED', 'USER_FOLLOWED'), ('SNIPPET_CREATED', 'SNIPPET_CREATED'), ('PERMISSION_GRANTED', 'PERMISSION_GRANTED'), ('PERMISSION_REVOKED', 'PERMISSION_REVOKED')], max_length=20),
        ),
    ]
