# Generated by Django 3.1 on 2020-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of',
            field=models.CharField(choices=[('USER_FOLLOWED', 'USER_FOLLOWED'), ('SNIPPET_CREATED', 'SNIPPET_CREATED'), ('PERMISSION_GRANTED', 'PERMISSION_GRANTED'), ('PERMISSION_REVOKED', 'PERMISSION_REVOKED'), ('COMMENT_CREATED', 'COMMENT_CREATED'), ('NEW_FOLLOWER', 'NEW_FOLLOWER'), ('FOLLOWER_INTERACT', 'FOLLOWER_INTERACT')], max_length=20),
        ),
    ]
